// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
    public static void main(String[] args) {
        int testNumber = Integer.parseInt(args[0]);
        int i = 0;
        int firstOption = 0;
        int secondOption = 0;
        double ratio = 0.0;
        while (i < testNumber) {
            double randomNumber = Math.random(); 
            if (randomNumber > 0.5) {
                firstOption++;
            } else {
                secondOption++;
            }
            i++;
        }

        if (secondOption != 0 || firstOption != 0) {
            ratio = (double) firstOption / secondOption;
        } else {
            ratio = 0; 
        }

        if (ratio == 0) {
            System.out.println("> 0.5: " + firstOption + " times, <= 0.5: " + secondOption);
        } else {
            System.out.println("> 0.5: " + firstOption + " times, <= 0.5: " + secondOption + " times, ratio: " + ratio);
        }
    }
}
